# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d61a1b95c7a2c88997f15c53ae4485e92754ec85a40f2904f6a68c4840eea3d5aad6d6893dbc861f9a703d4cd4487baddcbc19076eb8ec3be775c06c69568e5d

test:
  secret_key_base: 44205e73597a0996f257d808bf4a4a81ba97fd29d67e090646cbcf16073983b0885ca3e71f57892129d6b987ea59d4ed20c9b22f06985519cdfbc311daada61f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
