#!/bin/bash

if [ -e $HOME/.Xresources ]; then
  xrdb $HOME/.Xresources
fi
xsetroot -solid grey

export XSTARTUP_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
/usr/bin/fvwm -f ${XSTARTUP_DIR}/fvwm/fvwmrc &

. /etc/profile.d/lmod.sh
module load virtualgl/2.3

module use /nfs/gpfs/PZS0645/local-oakley/share/modulefiles
module load paraview/4.4.0

vglrun paraview --data=${DATAFILE}

vncserver -kill ${DISPLAY}
